url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/
# Site settings
title: Elevare Digital
description: Curated products with creative value — discover tech, fashion, and lifestyle gear with a twist.
url: "https://elevaredigital.great-site.net" # Your custom domain
baseurl: "" # Leave empty for root

# Author info
author:
  name: Dawit
  email: elevaredigital@gmail.com
  location: Addis Ababa, Ethiopia

# Social links
social:
  twitter: elevaredigital
  instagram: elevaredigital
  facebook: elevaredigital
  linkedin: dawit-elevare
  github: dabron9

# Build settings
markdown: kramdown
theme: minima # You can change this if using a custom theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO settings
seo:
  name: Elevare Digital
  description: Discover curated affiliate products with added value — tech, fashion, and lifestyle gear.
  url: "https://elevaredigital.great-site.net"
  twitter: elevaredigital
  facebook: elevaredigital

# Navigation links
nav:
  - title: Home
    url: /
  - title: Shop
    url: /shop/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# Collections
collections:
  products:
    output: true
    permalink: /shop/:name/

# Defaults for product pages
defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product
      author: Dawit
      category: curated

# Permalinks
permalink: pretty

# Google Analytics (optional)
google_analytics: UA-XXXXXXXXX-X # Replace with your tracking ID

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

